# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='event.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x65vent.proto\"@\n\x10SerializedObject\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08revision\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\xa0\x01\n\rMetaDataValue\x12\x14\n\ntext_value\x18\x01 \x01(\tH\x00\x12\x16\n\x0cnumber_value\x18\x02 \x01(\x12H\x00\x12\x17\n\rboolean_value\x18\x03 \x01(\x08H\x00\x12\x16\n\x0c\x64ouble_value\x18\x04 \x01(\x01H\x00\x12(\n\x0b\x62ytes_value\x18\x05 \x01(\x0b\x32\x11.SerializedObjectH\x00\x42\x06\n\x04\x64\x61ta\"\xaf\x02\n\x05\x45vent\x12\x1a\n\x12message_identifier\x18\x01 \x01(\t\x12\x1c\n\x14\x61ggregate_identifier\x18\x02 \x01(\t\x12!\n\x19\x61ggregate_sequence_number\x18\x03 \x01(\x03\x12\x16\n\x0e\x61ggregate_type\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\"\n\x07payload\x18\x06 \x01(\x0b\x32\x11.SerializedObject\x12\'\n\tmeta_data\x18\x07 \x03(\x0b\x32\x14.Event.MetaDataEntry\x12\x10\n\x08snapshot\x18\x08 \x01(\x08\x1a?\n\rMetaDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.MetaDataValue:\x02\x38\x01\x62\x06proto3'
)




_SERIALIZEDOBJECT = _descriptor.Descriptor(
  name='SerializedObject',
  full_name='SerializedObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SerializedObject.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='revision', full_name='SerializedObject.revision', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='SerializedObject.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=79,
)


_METADATAVALUE = _descriptor.Descriptor(
  name='MetaDataValue',
  full_name='MetaDataValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text_value', full_name='MetaDataValue.text_value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number_value', full_name='MetaDataValue.number_value', index=1,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='boolean_value', full_name='MetaDataValue.boolean_value', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='double_value', full_name='MetaDataValue.double_value', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bytes_value', full_name='MetaDataValue.bytes_value', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='MetaDataValue.data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=82,
  serialized_end=242,
)


_EVENT_METADATAENTRY = _descriptor.Descriptor(
  name='MetaDataEntry',
  full_name='Event.MetaDataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Event.MetaDataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Event.MetaDataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=485,
  serialized_end=548,
)

_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_identifier', full_name='Event.message_identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aggregate_identifier', full_name='Event.aggregate_identifier', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aggregate_sequence_number', full_name='Event.aggregate_sequence_number', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aggregate_type', full_name='Event.aggregate_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Event.timestamp', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='Event.payload', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meta_data', full_name='Event.meta_data', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='snapshot', full_name='Event.snapshot', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EVENT_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=548,
)

_METADATAVALUE.fields_by_name['bytes_value'].message_type = _SERIALIZEDOBJECT
_METADATAVALUE.oneofs_by_name['data'].fields.append(
  _METADATAVALUE.fields_by_name['text_value'])
_METADATAVALUE.fields_by_name['text_value'].containing_oneof = _METADATAVALUE.oneofs_by_name['data']
_METADATAVALUE.oneofs_by_name['data'].fields.append(
  _METADATAVALUE.fields_by_name['number_value'])
_METADATAVALUE.fields_by_name['number_value'].containing_oneof = _METADATAVALUE.oneofs_by_name['data']
_METADATAVALUE.oneofs_by_name['data'].fields.append(
  _METADATAVALUE.fields_by_name['boolean_value'])
_METADATAVALUE.fields_by_name['boolean_value'].containing_oneof = _METADATAVALUE.oneofs_by_name['data']
_METADATAVALUE.oneofs_by_name['data'].fields.append(
  _METADATAVALUE.fields_by_name['double_value'])
_METADATAVALUE.fields_by_name['double_value'].containing_oneof = _METADATAVALUE.oneofs_by_name['data']
_METADATAVALUE.oneofs_by_name['data'].fields.append(
  _METADATAVALUE.fields_by_name['bytes_value'])
_METADATAVALUE.fields_by_name['bytes_value'].containing_oneof = _METADATAVALUE.oneofs_by_name['data']
_EVENT_METADATAENTRY.fields_by_name['value'].message_type = _METADATAVALUE
_EVENT_METADATAENTRY.containing_type = _EVENT
_EVENT.fields_by_name['payload'].message_type = _SERIALIZEDOBJECT
_EVENT.fields_by_name['meta_data'].message_type = _EVENT_METADATAENTRY
DESCRIPTOR.message_types_by_name['SerializedObject'] = _SERIALIZEDOBJECT
DESCRIPTOR.message_types_by_name['MetaDataValue'] = _METADATAVALUE
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SerializedObject = _reflection.GeneratedProtocolMessageType('SerializedObject', (_message.Message,), {
  'DESCRIPTOR' : _SERIALIZEDOBJECT,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:SerializedObject)
  })
_sym_db.RegisterMessage(SerializedObject)

MetaDataValue = _reflection.GeneratedProtocolMessageType('MetaDataValue', (_message.Message,), {
  'DESCRIPTOR' : _METADATAVALUE,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:MetaDataValue)
  })
_sym_db.RegisterMessage(MetaDataValue)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {

  'MetaDataEntry' : _reflection.GeneratedProtocolMessageType('MetaDataEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVENT_METADATAENTRY,
    '__module__' : 'event_pb2'
    # @@protoc_insertion_point(class_scope:Event.MetaDataEntry)
    })
  ,
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:Event)
  })
_sym_db.RegisterMessage(Event)
_sym_db.RegisterMessage(Event.MetaDataEntry)


_EVENT_METADATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
